# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='cogment_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x0b\x63ogment_app\"\x0b\n\tEnvConfig\"9\n\x0bTrialConfig\x12*\n\nenv_config\x18\x01 \x01(\x0b\x32\x16.cogment_app.EnvConfig\"\x1b\n\x0bObservation\x12\x0c\n\x04time\x18\x01 \x01(\x02\"\x0c\n\nEmmaAction\"\x1a\n\nTimeAction\x12\x0c\n\x04time\x18\x01 \x01(\x02\x62\x06proto3')
)




_ENVCONFIG = _descriptor.Descriptor(
  name='EnvConfig',
  full_name='cogment_app.EnvConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=38,
)


_TRIALCONFIG = _descriptor.Descriptor(
  name='TrialConfig',
  full_name='cogment_app.TrialConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='env_config', full_name='cogment_app.TrialConfig.env_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=97,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='cogment_app.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='cogment_app.Observation.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=126,
)


_EMMAACTION = _descriptor.Descriptor(
  name='EmmaAction',
  full_name='cogment_app.EmmaAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=140,
)


_TIMEACTION = _descriptor.Descriptor(
  name='TimeAction',
  full_name='cogment_app.TimeAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='cogment_app.TimeAction.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=168,
)

_TRIALCONFIG.fields_by_name['env_config'].message_type = _ENVCONFIG
DESCRIPTOR.message_types_by_name['EnvConfig'] = _ENVCONFIG
DESCRIPTOR.message_types_by_name['TrialConfig'] = _TRIALCONFIG
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['EmmaAction'] = _EMMAACTION
DESCRIPTOR.message_types_by_name['TimeAction'] = _TIMEACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvConfig = _reflection.GeneratedProtocolMessageType('EnvConfig', (_message.Message,), dict(
  DESCRIPTOR = _ENVCONFIG,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:cogment_app.EnvConfig)
  ))
_sym_db.RegisterMessage(EnvConfig)

TrialConfig = _reflection.GeneratedProtocolMessageType('TrialConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRIALCONFIG,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:cogment_app.TrialConfig)
  ))
_sym_db.RegisterMessage(TrialConfig)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVATION,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:cogment_app.Observation)
  ))
_sym_db.RegisterMessage(Observation)

EmmaAction = _reflection.GeneratedProtocolMessageType('EmmaAction', (_message.Message,), dict(
  DESCRIPTOR = _EMMAACTION,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:cogment_app.EmmaAction)
  ))
_sym_db.RegisterMessage(EmmaAction)

TimeAction = _reflection.GeneratedProtocolMessageType('TimeAction', (_message.Message,), dict(
  DESCRIPTOR = _TIMEACTION,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:cogment_app.TimeAction)
  ))
_sym_db.RegisterMessage(TimeAction)


# @@protoc_insertion_point(module_scope)
