trial_params:
  environment:
    endpoint: grpc://localhost:9001

  actors:
    - name: client_actor
      actor_class: client
      endpoint: cogment://client
    - name: echo_echo_1
      actor_class: echo
      implementation: echo
      endpoint: grpc://localhost:9002
