image: docker:19.03.14

default:
  tags:
    - ai-r
    - docker

stages:
  - test
  - build
  - release

test:
  stage: test
  script:
    - apk add docker-compose protoc
    - docker-compose run --build cogment-js-sdk npm run test:ci
  variables:
    NODE_ENV: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage
    reports:
      junit: junit.xml

build:
  stage: build
  before_script:
    - apk add docker-compose protoc
  script:
    - docker-compose run --build cogment-js-sdk npm run build
  artifacts:
    paths:
      - dist
      - public

pages:
  stage: release
  script:
    - cp -r coverage public/coverage
  artifacts:
    paths:
      - public
  only:
    - master

#release:gitlab:
#  stage: release
#  script:
#    - npm run release

release:npm:tag:
  stage: release
  script:
    - echo "This job releases something from the $CI_COMMIT_BRANCH branch."
  only:
    - develop

release:npm:beta:
  stage: release
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - develop

release:npm:
  stage: release
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - master
