image: docker:20.10.3

variables:
  COMPOSE_PROJECT_NAME: ${CI_JOB_ID}

default:
  tags:
    - ai-r
    - docker

stages:
  - lint
  - test
  - build
  - publish
  - pages

.base_gh_ssh_agent:
  before_script:
    ## _Inspired by https://docs.gitlab.com/ee/ci/ssh_keys/_
    ##
    ## Install ssh-agent if not already installed.
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    ## Run ssh-agent
    - eval $(ssh-agent -s)
    ## Add the private key file to ssh-agent
    - echo "$GH_REPO_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    ## Using the set $SSH_KNOWN_HOSTS to be able to verify remote servers public keys
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

shellcheck:
  image: koalaman/shellcheck-alpine:stable
  stage: lint
  before_script:
    - shellcheck --version
  script:
    - shellcheck ./scripts/*.sh

shfmt:
  image: mvdan/shfmt:v3.1.0-alpine
  stage: lint
  before_script:
    - shfmt -version
  script:
    - shfmt -i 2 -ci -d ./scripts

pre:install:
  stage: .pre
  image: node:14
  script:
    - npm install -g npm
    - npm install
    - pushd cli && npm install && popd
    - pushd __tests__/end-to-end/cogment-app/webapp && npm install && popd
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - cli/node_modules
      - __tests__/end-to-end/cogment-app/webapp/node_modules

lint_js:
  image: node:14
  stage: lint
  script:
    - npm install -g npm
    - npm install
    - pushd cli && npm install && popd
    - npm run lint:ci

test:
  stage: test
  variables:
    NODE_ENV: test
    COMPOSE_FILE: docker-compose.yaml
  before_script:
    - apk add bash docker-compose
    - docker system prune -af --volumes
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build cogment-js-sdk
    - bin/up.bash
  script:
    - docker-compose run -e NODE_ENV=test cogment-js-sdk npm run test:ci
  after_script:
    - docker-compose logs --no-color --tail all > docker.log
    - docker-compose stop
    - mkdir -p public
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/allure-report ./public/allure
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/coverage ./public/coverage
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/src/cogment/api ./src/cogment/api
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/junit.xml ./junit.xml
    - docker-compose down
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    expose_as: reports
    expire_in: 1 day
    paths:
      - src/cogment/api
      - public
      - docker.log
    reports:
      junit: junit.xml
    when: always

build_docker:
  stage: build
  before_script:
    - apk add docker-compose
  script:
    - docker-compose run -e NODE_ENV=production -e CI=true cogment-js-sdk npm run build
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/dist ./dist
    - mkdir -p public
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/allure-report ./public/allure
    - docker cp $(docker-compose ps -a -q cogment-js-sdk):/app/coverage ./public/coverage
  artifacts:
    expire_in: 1 day
    paths:
      - dist
      - public

dry_run_publish_tag_to_npm:
  image: node:14
  stage: build
  variables:
    NODE_ENV: production
  script:
    - npm publish --dry-run

publish_tag_to_npm:
  image: node:14
  stage: publish
  variables:
    NODE_ENV: production
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(?:-[[:alnum:]]+)?$/

publish_branch_to_github:
  image: node:14 # No node usage here but git is required (and part of this image)
  extends: .base_gh_ssh_agent
  stage: publish
  script:
    - git checkout ${CI_COMMIT_BRANCH} # Checkout the branch not the sha1
    - git remote add downstream git@github.com:cogment/cogment-js-sdk.git
    - git fetch downstream ${CI_COMMIT_BRANCH}
    - git push --tags downstream ${CI_COMMIT_BRANCH}:${CI_COMMIT_BRANCH}
  only:
    - main

pages:
  stage: pages
  variables:
    NODE_ENV: production
  before_script:
    - apk add docker-compose
  script:
    - echo "Generating Gitlab pages"
  artifacts:
    paths:
      - public
  only:
    - develop
