include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: node:14

stages:
  - build
  - test
  - deploy

variables:
  PROTOC_URL: https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
  DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64

.ssh:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$COGMENT_API_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

.cache:docker-compose:
  cache:
    key: ${DOCKER_COMPOSE_URL}
    paths:
      - docker-compose

.cache:protoc:
  cache:
    key: ${PROTOC_URL}
    paths:
      - protoc

pre:download-docker-compose:
  stage: .pre
  extends:
    - .cache:docker-compose
  script:
    - apt-get update -y
    - apt-get install curl unzip -y
    - curl -LSso docker-compose ${DOCKER_COMPOSE_URL}

pre:download-protoc:
  stage: .pre
  extends:
    - .cache:protoc
  script:
    - apt-get update -y
    - apt-get install curl unzip -y
    - curl -LSso protoc.zip ${PROTOC_URL}
    - unzip -od protoc protoc.zip

pre:npm-install:
  stage: .pre
  extends:
    - .ssh
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  extends:
    - .cache:protoc
  before_script:
    - cp -r protoc/{bin,include} /usr/local/
  script:
    - npm run build
  artifacts:
    paths:
      - src/cogment/api
      - dist
      - public

test:
  stage: test
  extends:
    - .cache:docker-compose
  before_script:
    - install -m 0755 docker-compose /usr/local/bin/docker-compose
  script:
    - npm run test
  variables:
    NODE_ENV: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage
    reports:
      junit: junit.xml

pages:
  stage: deploy
  script:
    - apt update && apt install -y lcov gcc
    - npm run --silent test:codecov
    - cp -r coverage public/coverage
  artifacts:
    paths:
      - public
  only:
    - master

package:npm:beta:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - develop

package:npm:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - master
