image: docker:20.10.3

variables:
  COMPOSE_PROJECT_NAME: ${CI_JOB_ID}

default:
  tags:
    - ai-r
    - docker

stages:
  - test
  - build
  - release
  - pages

pre:install:
  stage: .pre
  image: node:14
  script:
    - npm install -g npm
    - npm install
    - pushd cli && npm install && popd
    - pushd __tests__/end-to-end/cogment-app/webapp && npm install && popd
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - cli/node_modules
      - __tests__/end-to-end/cogment-app/webapp/node_modules

test:
  stage: test
  variables:
    NODE_ENV: test
    COMPOSE_FILE: docker-compose.yaml
  before_script:
    - apk add bash docker-compose
    - docker network prune -f
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build cogment-js-sdk
    - docker-compose run cogment-js-sdk npm run init
    - bin/up.bash
  script:
    - docker-compose run -e NODE_ENV=test cogment-js-sdk npm run test:ci
  after_script:
    - docker-compose logs --no-color --tail all > docker.log
    - bin/down.bash
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    expose_as: reports
    expire_in: 1 day
    paths:
      - src/cogment/api
      - coverage
      - allure-report
      - docker.log
    reports:
      junit: junit.xml
    when: always

build:
  stage: build
  before_script:
    - apk add docker-compose
  script:
    - docker-compose run -e NODE_ENV=production -e CI=true cogment-js-sdk npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist
      - public

release:
  stage: release
  image: node:14
  variables:
    NODE_ENV: production
  before_script:
    - mkdir -pm 0700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "${GIT_SSH_PRIVATE_KEY}" | ssh-add -
  script:
    - git checkout "${CI_COMMIT_BRANCH}"
    - git remote add downstream git@github.com:cogment/cogment-js-sdk.git
    - git fetch downstream ${CI_COMMIT_BRANCH}
    - git push downstream ${CI_COMMIT_BRANCH}
    - npm run semantic-release
  only:
    - main
    - next
    - alpha
    - beta

pages:
  stage: pages
  variables:
    NODE_ENV: production
  before_script:
    - apk add docker-compose
  script:
    - docker-compose run -e NODE_ENV=production -e CI=true cogment-js-sdk npm run build:docs
    - cp -r allure-report public/allure
    - cp -r coverage public/coverage
    - cp -r docs/api/* public/
  artifacts:
    paths:
      - public
  only:
    - develop
