image: node:14

stages:
  - lint
  - build
  - test
  - deploy

variables:
  PROTOC_URL: https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip

.ssh:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$COGMENT_API_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

.cache:protoc:
  cache:
    key: ${PROTOC_URL}
    paths:
      - protoc

prebuild:download-protoc:
  stage: .pre
  extends:
    - .cache:protoc
  script:
    - apt-get update -y
    - apt-get install curl unzip -y
    - curl -LSso protoc.zip "${PROTOC_URL}"
    - unzip -od protoc protoc.zip

prebuild:npm-install:
  stage: .pre
  extends:
    - .ssh
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  extends:
    - .cache:protoc
  before_script:
    - cp -r protoc/{bin,include} /usr/local/
  script:
    - npm run build
  artifacts:
    paths:
      - src/cogment/api

test:
  stage: test
  script:
    - npm run test
  variables:
    NODE_ENV: test
  coverage: '/Lines\s*:\s*(\d+.\d+)%\s*\(\s*\d+\/\d+\s*\)/'
  #  coverage: '/All files\s*\|\s*\d+\s*\|\s*\d+\s*\|\s*\d+\s*\|\s*(\d+)\s*/'
  artifacts:
    paths:
      - coverage
    reports:
      junit: junit.xml

pages:
  stage: deploy
  script:
    - npm run docs
    - cp -r coverage/lcov-report public/coverage
  artifacts:
    paths:
      - public
  only:
    - master

package:npm:beta:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - develop

package:npm:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - master
