version: '3.7'

services:
  grpc-cli:
    image: namely/grpc-cli:1.32_1

  cogment-cli:
    image: registry.gitlab.com/ai-r/cogment-cli:latest
    volumes:
      - ./:/cogment

  cogment-js-sdk:
    image: registry.gitlab.com/ai-r/cogment-js-sdk/cogment-js-sdk:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 4000:4000/tcp

  time:
    image: registry.gitlab.com/ai-r/change_me/time:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: agents/time/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1
    x-cogment:
      ports:
        - port: 9000
    restart: on-failure

  env:
    image: registry.gitlab.com/ai-r/change_me/env:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: envs/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1
    x-cogment:
      ports:
        - port: 9000
    restart: on-failure

  orchestrator:
    image: registry.gitlab.com/ai-r/change_me/orchestrator:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: orchestrator/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/.:/app
    x-cogment:
      ports:
        - port: 9000
    depends_on:
      - env
      - time
    restart: on-failure

  grpcwebproxy:
    build:
      context: ./__tests__/end-to-end/cogment-app/grpcwebproxy
    depends_on:
      - orchestrator
    restart: on-failure

  sonarqube:
    image: sonarqube:latest
    stop_grace_period: 3600s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - 9001:9000/tcp
    depends_on:
      - postgres

  sonarqube-scan:
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_LOGIN: 7c5ed1c4077292688ef483cd61b0bc65735c23a3
    volumes:
      - .:/usr/src
    depends_on:
      - sonarqube

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_extensions:
    driver: local
