version: '3.7'

services:
  grpc-cli:
    image: namely/grpc-cli:latest

  cogment-cli:
    image: registry.gitlab.com/cogment-cli:latest
    volumes:
      - ./:/cogment

  cogment-js-sdk:
    image: registry.gitlab.com/ai-r/cogment-js-sdk-1.0/cogment-js-sdk:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 4000:4000/tcp

  time:
    image: registry.gitlab.com/ai-r/change_me/time:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: agents/time/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1
    x-cogment:
      ports:
        - port: 9000

  env:
    image: registry.gitlab.com/ai-r/change_me/env:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: envs/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      - COGMENT_GRPC_REFLECTION=1
      - PYTHONUNBUFFERED=1
    x-cogment:
      ports:
        - port: 9000

  orchestrator:
    image: registry.gitlab.com/ai-r/change_me/orchestrator:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: orchestrator/Dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/.:/app
    x-cogment:
      ports:
        - port: 9000
    depends_on:
      - env
      - time

  grpcwebproxy:
    build:
      context: ./__tests__/end-to-end/cogment-app/grpcwebproxy
    depends_on:
      - orchestrator
