version: '3.7'

services:
  grpc-cli:
    image: namely/grpc-cli:1.32_1

  cogment-cli:
    image: cogment/cli:v1.0.0-alpha9
    volumes:
      - ./:/cogment

  cogment-js-sdk:
    image: registry.gitlab.com/ai-r/cogment-js-sdk/cogment-js-sdk:latest
    build:
      context: .

  client:
    build:
      context: __tests__/end-to-end/cogment-app/client
      dockerfile: ../py_service.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  echo:
    image: registry.gitlab.com/ai-r/change_me/echo:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/echo
      dockerfile: ../py_service.dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      COGMENT_GRPC_REFLECTION: 1
      PYTHONUNBUFFERED: 1
    x-cogment:
      ports:
        - port: 9000
    restart: on-failure

  environment:
    image: registry.gitlab.com/ai-r/change_me/environment:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/environment
      dockerfile: ../py_service.dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      COGMENT_GRPC_REFLECTION: 1
      PYTHONUNBUFFERED: 1
    x-cogment:
      ports:
        - port: 9000
    restart: on-failure

  configurator:
    image: registry.gitlab.com/ai-r/change_me/configurator:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/configurator
      dockerfile: ../py_service.dockerfile
    volumes:
      - ./__tests__/end-to-end/cogment-app/:/app
    environment:
      COGMENT_GRPC_REFLECTION: 1
      PYTHONUNBUFFERED: 1
    x-cogment:
      ports:
        - port: 9000
    restart: on-failure

  orchestrator:
    image: registry.gitlab.com/ai-r/change_me/orchestrator:latest
    build:
      context: ./__tests__/end-to-end/cogment-app/
      dockerfile: orchestrator.dockerfile
    x-cogment:
      ports:
        - port: 9000
    depends_on:
      - environment
      - echo
      - configurator
    restart: on-failure

  grpcwebproxy:
    build:
      context: ./__tests__/end-to-end/cogment-app
      dockerfile: grpcwebproxy.dockerfile
    depends_on:
      - orchestrator
    restart: on-failure
    ports:
      - 8080:8080/tcp