version: '3.7'

services:
  grpc-cli:
    image: namely/grpc-cli:latest

  cogment-cli:
    image: registry.gitlab.com/ai-r/cogment-cli:latest
    volumes:
      - ./:/cogment

  cogment-js-sdk:
    image: registry.gitlab.com/ai-r/cogment-js-sdk-1.0/cogment-js-sdk:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 4000:4000/tcp
