version: '3.8'

services:
  grpc-cli:
    image: namely/grpc-cli:1.28_1

  cogment-cli:
    image: registry.gitlab.com/cogment/cogment/cli
    volumes:
      - ./:/app

  cogment-js-sdk:
    image: registry.gitlab.com/ai-r/cogment-js-sdk-1.0/cogment-js-sdk:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 4000:4000/tcp
