# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class EnvConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___EnvConfig = EnvConfig

class TrialConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def env_config(self) -> type___EnvConfig: ...

    def __init__(self,
        *,
        env_config : typing___Optional[type___EnvConfig] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"env_config",b"env_config"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"env_config",b"env_config"]) -> None: ...
type___TrialConfig = TrialConfig

class Observation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    timestamp: builtin___int = ...
    request: typing___Text = ...
    response: typing___Text = ...

    def __init__(self,
        *,
        timestamp : typing___Optional[builtin___int] = None,
        request : typing___Optional[typing___Text] = None,
        response : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"request",b"request",u"response",b"response",u"timestamp",b"timestamp"]) -> None: ...
type___Observation = Observation

class ClientAction(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    request: typing___Text = ...

    def __init__(self,
        *,
        request : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"request",b"request"]) -> None: ...
type___ClientAction = ClientAction

class EchoAction(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    response: typing___Text = ...

    def __init__(self,
        *,
        response : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"response",b"response"]) -> None: ...
type___EchoAction = EchoAction
